{% set name = "dlhub-sdk" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DLHub-Argonne/dlhub_sdk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 511533f3b2df03c93f4eb165e63665606aee14665a433fe30cd79517762e5a2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - funcx >=0.3.6
    - globus-sdk <4,>=3
    - jsonschema >=3.2.0
    - mdf_toolbox >=0.5.4
    - pydantic
    - python >=3.4
    - requests >=2.24.0
    - numpy

test:
  imports:
    - dlhub_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DLHub-Argonne/dlhub_sdk
  summary: Python interface and utilities for DLHub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
