{% set name = "dlhub-sdk" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DLHub-Argonne/dlhub_sdk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d20d2f653f543ee7b344e5c64c78835ef496faa41ef71975e388babef0ad9cf3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - globus-sdk <4,>=3
    - requests >=2.24.0
    - mdf_toolbox >=0.5.4
    - jsonschema >=3.2.0
    - globus-compute-sdk >=2.0.0
    - pydantic
    - numpy
    - pygithub

test:
  imports:
    - dlhub_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DLHub-Argonne/dlhub_sdk
  summary: Python interface and utilities for DLHub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
